######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 16 19:21:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += button.h filelist.h key.h piechartqt.h
SOURCES += button.cpp filelist.cpp key.cpp main.cpp piechartqt.cpp
